### ISSUE TITLE
how can I show banner ads? 

### ISSUE THREAD

**Issue by jffs** [notmedia/cordova-plugin-adcolony#4]
Hey, Im trying to use this plugin to show some Ads. For Rewarded Ads works well (AdColony's Ads is shown), but if i change the Zone to one with banner ad configuration. I get an error "AdColonyPlugin: Request interstitial failed with error"

**Comment by notmedia** [comment]
Hi, please provide me the full text of error.

You have event AdColonyRequestNotFilled, where you log it.
